# Generated by Django 5.0 on 2023-12-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_signup_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='contact',
        ),
    ]
